[workspace]
members = [ 
    "ptys-iced", 
    "ptys-network",
]
resolver = "2"

[workspace.dependencies]
async-trait = "0.1.83"
eyre = "0.6.12"
iced = "0.13.1"
tokio = "1.42.0"
tokio-util = "0.7.13"
