[package]
name = "ptys_packets"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
num-bigint = "0.4.4"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
