import { Button } from "std-widgets.slint";
import { AddListenerState } from "AddListenerState.slint";

export component AddListener {
    VerticalLayout {
        Text {
            text: "Add listener";
        }

        port_input := TextInput {
            text: "1234";
        }

        Button {
            text: "Add listener";
            clicked => { AddListenerState.add-listener-pressed(port_input.text) }
        }

        Text {
            text: AddListenerState.add-listener-result;
        }
    }
}