[package]
name = "rust_lib_ptys_app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
ptys_network = { path = "../ptys_network" }
tokio = { workspace = true }
flutter_rust_bridge = "=2.7.0"
