[package]
name = "ptys-iced"
version = "0.1.0"
edition = "2021"

[dependencies]
ptys-network = { path = "../ptys-network" }
eyre = { workspace = true }
iced = { workspace = true, features = ["tokio"] }
tokio = { workspace = true }