import { ListenerListState } from "ListenerListState.slint";

export component ListenerList {
    VerticalLayout {
        Text {
            text: "Listener list:";
        }
        
        for listener in ListenerListState.entries: HorizontalLayout {
            Text {
                text: listener.id;
            }
            Text {
                text: listener.state;
            }
        }
    }
}